# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 294)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cb_variety = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_variety.setFont(font)
        self.cb_variety.setObjectName("cb_variety")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_variety)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_id = QtWidgets.QLineEdit(self.centralwidget)
        self.le_id.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_id.setFont(font)
        self.le_id.setStyleSheet("color: black")
        self.le_id.setObjectName("le_id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_id)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_degree = QtWidgets.QLineEdit(self.centralwidget)
        self.le_degree.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_degree.setFont(font)
        self.le_degree.setStyleSheet("color: black")
        self.le_degree.setObjectName("le_degree")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_degree)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_type = QtWidgets.QLineEdit(self.centralwidget)
        self.le_type.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_type.setFont(font)
        self.le_type.setStyleSheet("color: black")
        self.le_type.setObjectName("le_type")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_type)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_taste = QtWidgets.QLineEdit(self.centralwidget)
        self.le_taste.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_taste.setFont(font)
        self.le_taste.setStyleSheet("color: black")
        self.le_taste.setObjectName("le_taste")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_taste)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_price = QtWidgets.QLineEdit(self.centralwidget)
        self.le_price.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_price.setFont(font)
        self.le_price.setStyleSheet("color: black")
        self.le_price.setObjectName("le_price")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_price)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_volume = QtWidgets.QLineEdit(self.centralwidget)
        self.le_volume.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_volume.setFont(font)
        self.le_volume.setStyleSheet("color: black")
        self.le_volume.setObjectName("le_volume")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_volume)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_add = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_add.setFont(font)
        self.pb_add.setObjectName("pb_add")
        self.horizontalLayout.addWidget(self.pb_add)
        self.pb_edit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_edit.setFont(font)
        self.pb_edit.setObjectName("pb_edit")
        self.horizontalLayout.addWidget(self.pb_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Сорт кофе"))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "Степень обжарки"))
        self.label_4.setText(_translate("MainWindow", "Вид кофе"))
        self.label_5.setText(_translate("MainWindow", "Вкус"))
        self.label_6.setText(_translate("MainWindow", "Цена"))
        self.label_7.setText(_translate("MainWindow", "Объем упаковки"))
        self.pb_add.setText(_translate("MainWindow", "Добавить"))
        self.pb_edit.setText(_translate("MainWindow", "Изменить"))
